name: Build and deploy to staging ut1 when pull request is created

on:
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build and deploy to ut1 environment

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '270.0.0'
          service_account_email: ${{ secrets.GCP_SA_FDK_JENKINS_GCR_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_FDK_JENKINS_GCR }}

      # Configure docker to use the gcloud command-line tool as a credential helper
      - run: gcloud auth configure-docker

      - name: Build Docker image with GitHub commit sha tag
        run: docker build . -t eu.gcr.io/fdk-infra/fdk-nginx-enhetsregisteret-proxy-mock:$GITHUB_SHA -t eu.gcr.io/fdk-infra/fdk-nginx-enhetsregisteret-proxy-mock:staging_latest

      - name: Publish docker image to Google Cloud
        run: docker -- push eu.gcr.io/fdk-infra/fdk-nginx-enhetsregisteret-proxy-mock

      - name: Apply Helm template
        uses: stefanprodan/kube-tools@v1
        with:
          helm: 2.14.3
          command: |
            helm init --client-only
            helm repo add fdk https://informasjonsforvaltning.github.io/helm-chart/
            helm fetch --untar --untardir ./helm fdk/fdk-nginx-enhetsregisteret-proxy-mock
            helm template --set DOCKER_IMAGE_NAME="eu.gcr.io/fdk-infra/fdk-nginx-enhetsregisteret-proxy-mock:$GITHUB_SHA" -f ./helm/fdk-nginx-enhetsregisteret-proxy-mock/values/staging-ut1.yaml ./helm/fdk-nginx-enhetsregisteret-proxy-mock/ > ./kubectlapply.yaml
            cat ./kubectlapply.yaml
            chmod o+w ./kubectlapply.yaml
            cat kubectlapply.yaml

      - name: Get kubeconfig file from GKE
        uses: machine-learning-apps/gke-kubeconfig@master
        with:
          application_credentials: ${{ secrets.FDK_DEV_AUTODEPLOY }}
          project_id: fdk-dev
          location_zone: europe-north1-a
          cluster_name: fdk-dev

      - name: Deploy to staging-ut1
        uses: docker://bitnami/kubectl:latest
        env:
          KUBECONFIG: '/github/workspace/.kube/config'
        with:
          args: "apply -f ./kubectlapply.yaml --force"